### ISSUE TITLE
How to use plugin iframeTracker?

### ISSUE THREAD

**Issue by dimti** [vincepare/iframeTracker-jquery#14]
My problem - enspect how to count clicks on adsense banners on my site (http://help-me-now.ru/)

I use plugin iframeTracker and write that code:

    jQuery(document).ready(function(){
        jQuery('.adsbygoogle iframe').iframeTracker({
            blurCallback: function(){
                console.log('YYY');
            }
        });
    });

But, after click on banners - console not showing 'YYY' in log. Why?

http://i.imgur.com/sVl5NU5.png

**Comment by emrexhepi** [comment]
I had this problem at the beginning. Be sure that the iframe exists. If you are adding adsense as async, the iframe will not be there when you call "iframeTracker" therefore it does not have what to track.

My simple solution to this would be with setInterval();

interval_id = setInverval(function() {
   //check if iframe exists
   if( jQuery('.adsbygoogle iframe').length > 0 ) {
       jQuery('.adsbygoogle iframe').iframeTracker({
        blurCallback: function(){
            alert("You clicked on iframe");
        }
       });
       //clear the interval
       clearInterval(interval_id);
   }
},300);

I may have errors in my code, I did not have time to check it, but i hope you get the idea.
ps. use alerts for debugging when you expect the page to be redirected.

**Comment by dimti** [comment]
Thanks. Plugin work for me

I tracking clicks with piwik analytics

    <script src="https://code.jquery.com/jquery-1.11.3.min.js" type="application/javascript"></script>
    <script src="/bower_components/jquery.iframetracker/jquery.iframetracker.js" type="application/javascript"></script>
    <script type="text/javascript">
    jQuery(document).ready(function(){
        interval_id = window.setInterval(function() {
        //check if iframe exists
        if( jQuery('.adsbygoogle iframe').length > 0 ) {
            jQuery('.adsbygoogle iframe').iframeTracker({
                blurCallback: function(){
                    _paq.push(['trackEvent', 'AdSense', 'click', 'AdSense']);
                }
            });
            //clear the interval
            clearInterval(interval_id);
            }
        },300);
    });
    </script>

And see in piwik 
![Image of piwik](http://i.imgur.com/07RAn7Y.png)

Works!
