### ISSUE TITLE
Alert stops the Iframe event

### ISSUE THREAD

**Issue by shadyshrif** [vincepare/iframeTracker-jquery#16]
I was dubbing and using alert to check the blurCallback. My Iframe normally opens an external url. When I use Alert() it stops excuting the Iframe event. I don't know why?!!
`$('#myFrame').iframeTracker({ blurCallback: function () { alert('show'); } });`

I'm using chrome Version 50.0.2661.66 beta-m (64-bit)

**Comment by vincepare** [comment]
What do you mean by _it stops excuting the Iframe event_ ?
Do you mean that your code inside the `blurCallback` handler doesn't seem to be executed ?

I don't understand this : _My Iframe normally opens an external url_, are you talking about the `iframe`'s src attribute, or about a link inside the iframe document that breaks your blurCallback once clicked ?
In that latter case, does the `<a>` tag have a `target="_top"` attribute ?

**Comment by shadyshrif** [comment]
Actually I'm tracking google ads, I tried to put alert to give the user message before the ad is opened; But unfortunately the messages comes after the ad opens.

**Comment by vincepare** [comment]
When I use alert with iframeTracker like that :

```javascript
$('#iframe_dummyads iframe').iframeTracker({
    blurCallback: function(){
        alert("ads click");
    }
});
```

I just see the alert box when I click a link inside the google adsense iframe but nothing happen after closing the alert (click OK). In other words, I don't have the same behavior that the one you are describing.

I'm testing on `Google Chrome 50.0.2661.94 (Build officiel) m (32 bits)` / `0c319c380220abe3daf0277e40a2d0b22a7c4550-refs/branch-heads/2661@{#645}`.
