### ISSUE TITLE
Get closest iframe src using tracker

### ISSUE THREAD

**Issue by Pau1fitz** [vincepare/iframeTracker-jquery#17]
Hi, I am using this in Google Tag manager, and it is triggering, however, I do not have iframes with ids, so if a user clicks on an iframe I want to get the src of the iframe.

In GTM my code looks like the following. How can I access the iframe src in the callback function?

```
function(){
  $('iframe').iframeTracker({
    blurCallback: function(){
      //how can I get the iframe src in here?
    }
  });
}
```

**Comment by jirkace** [comment]
Anybody any solution?

**Comment by ericbae** [comment]
I think this will work

`function(){
  $('iframe').iframeTracker({
      iframeSrc: null,

      overCallback: function(element) {
        this.iframeSrc = $(element).attr('src');
     },

      outCallback: function(element) {
        this.iframeSrc = null;
     },

    blurCallback: function(){
      //how can I get the iframe src in here?
     console.log(this.iframeSrc) // this should print out the iframe src 
    }
  });
}`
