### ISSUE TITLE
Click tracking only works on first click

### ISSUE THREAD

**Issue by StevenFlecha** [vincepare/iframeTracker-jquery#18]
Hi,

Thanks for the great script! I'm having a small issue that the click tracker only works once.
So I mouse in and click and it works (I actually open a menu at this point). But then when the menu is closed and  a user clicks again in the iframe nothing happens (working with vid embeds here).

The problem is that blurCallback is not called. I need to mouse out of the iframe and mouse back to make blurCallback fire again on click.

I feel its prob an easy fix but haven't found it yet. Any pointers would be appreciated!

Thanks.

P.s. from reading the tutorial etc I thought '$(window).focus();' would reset it and catch the click but it doesn't :(

**Comment by vincepare** [comment]
Unfortunately, this is the expected behavior of the page/iframe boundary monitoring system. There is no way to prevent that because the focus cannot return back to the parent page while the mouse cursor is inside the iframe.
