### ISSUE TITLE
i want find click on the which element of iframe

### ISSUE THREAD

**Issue by aynaz96** [vincepare/iframeTracker-jquery#21]
I use your plugin for click on the frame. but I want to know click on which element such az button.  please help me.

**Comment by vincepare** [comment]
You can't do such a thing because, as the [README](https://github.com/vincepare/iframeTracker-jquery/blob/2.0.0/README.md) file states, parent page (where iframeTracker runs) cannot access child iframe content due to the [same origin policy](https://en.wikipedia.org/wiki/Same-origin_policy).
