### ISSUE TITLE
Ajax loaded forms IE7/IE8

### ISSUE THREAD

**Issue by jaykobi** [vincepare/iframeTracker-jquery#6]
In IE7/IE8 with jQuery 1.11.0 you cannot enter text in inputs created after document ready. 

If you click in such an input, it will lose focus immeditely.

Suggested fix: change line 77 to 
$('body').on('click', 'form', function(e){ e.stopPropagation(); });

**Comment by bluefox** [comment]
Not to re-open issues, but this fix actually prevents the use all document/body level click events in ASP.NET form, since the page is essentially a giant form and everything is inside the form.
